# Generated by Django 3.0.7 on 2020-06-11 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField()),
                ('text', models.CharField(max_length=200)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Moderate'), (3, 'Critical')], default=1)),
                ('est_time', models.IntegerField(default=0)),
                ('est_time_unit', models.IntegerField(choices=[(0, 'M'), (1, 'H')], default=1)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
